export const DetailTest = {
  lostPostId: 1,
  imageUrls: ["https://your-bucket.s3.ap-northeast-2.amazonaws.com/lostPosts/lostpost1.jpg",
    "/images/headset1.jpg",
    "/images/headset2.jpg",
    "/images/headset3.jpg",
    ],
  registrationType: "LOST",
  title: "소니 WH-1000XM4 헤드셋 찾아주세요!!!!!!!!!!!",
  memberImageUrl: "https://your-bucket.s3.ap-northeast-2.amazonaws.com/lostPosts/lostpost1.jpg",
  nickname: "유저 1",
  timeAgo: "3시간 전",
  lostLocationDong: "월계 1동",
  detailedLocation: "주민센터 앞",
  latitude: 37.5665,
  longitude: 126.978,
  reward: 10000,
  instantSettlement: true,
  description: "제사한 내용은 여기에 들어갑니다. 헤드셋 주웠어요 찾아가세요.제사한 내용은 여기에 들어갑니다. 헤드셋 주웠어요 찾아가세요.제사한 내용은 여기에 들어갑니다. 헤드셋 주웠어요 찾아가세요. ",
  category: "전자기기",
  itemName: "소니 WH-1000XM4",
  feature1: "빨간색",
  feature2: "새 제품",
  feature3: "스크래치 없음",
  feature4: "박스 포함",
  feature5: "정품",
  lostDateTimeStart: "2025-07-07T07:43:45.583Z",
  lostDateTimeEnd: "2025-07-07T08:43:45.583Z"
};